# Ce fichier YAML définit un déploiement Kubernetes pour WordPress dans le namespace `wp-ns`. 
# Le déploiement maintient deux répliques de l'application WordPress. 
# Chaque pod exécute un conteneur basé sur l'image `wordpress:latest` et expose le port 80. 
# Les variables d'environnement sont utilisées pour configurer l'application WordPress, y compris les détails de la base de données. 
# Le mot de passe de la base de données est stocké dans un Secret Kubernetes. 
# Un volume est monté dans le conteneur au chemin `/var/www/html`, mappé à un chemin sur l'hôte, permettant la persistance des données.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wp-ns
  labels:
    app: wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: "rds-mariadb.csingpkxfz9v.eu-west-1.rds.amazonaws.com"
        - name: WORDPRESS_DB_USER
          value: "wpuser"
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-db-secret
              key: password
        - name: WORDPRESS_DB_NAME
          value: "wordpressdb"
        volumeMounts:
        - name: wordpress-storage
          mountPath: "/var/www/html"
      volumes:
      - name: wordpress-storage
        hostPath:
          path: /var/www/wordpress-data
          type: DirectoryOrCreate
